// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ahHj32FavFt2Ah34HQ1orXu2bQ_ORgI',
    appId: '1:1788284331:web:54d34f958f45824d7056ee',
    messagingSenderId: '1788284331',
    projectId: 'ritchat-9674f',
    authDomain: 'ritchat-9674f.firebaseapp.com',
    storageBucket: 'ritchat-9674f.appspot.com',
    measurementId: 'G-96HKDSSRVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmD0mb1-9jHvfZna48jnvmckNo9WbJ1ow',
    appId: '1:1788284331:android:de3afb161edfb7217056ee',
    messagingSenderId: '1788284331',
    projectId: 'ritchat-9674f',
    storageBucket: 'ritchat-9674f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKImY_TBUgYn4XnMPXtZwGqMtmAf-D6GA',
    appId: '1:1788284331:ios:db612aa5dfe7dd817056ee',
    messagingSenderId: '1788284331',
    projectId: 'ritchat-9674f',
    storageBucket: 'ritchat-9674f.appspot.com',
    iosBundleId: 'com.example.ritchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKImY_TBUgYn4XnMPXtZwGqMtmAf-D6GA',
    appId: '1:1788284331:ios:db612aa5dfe7dd817056ee',
    messagingSenderId: '1788284331',
    projectId: 'ritchat-9674f',
    storageBucket: 'ritchat-9674f.appspot.com',
    iosBundleId: 'com.example.ritchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7ahHj32FavFt2Ah34HQ1orXu2bQ_ORgI',
    appId: '1:1788284331:web:360960ac7ee9a3ec7056ee',
    messagingSenderId: '1788284331',
    projectId: 'ritchat-9674f',
    authDomain: 'ritchat-9674f.firebaseapp.com',
    storageBucket: 'ritchat-9674f.appspot.com',
    measurementId: 'G-0ESEVRFB7J',
  );

}